### ISSUE TITLE
通过该生成器生成的Token传回客户端，客户端发起请求显示The supplied auth token was invalid

### ISSUE THREAD

**Issue by dingyiming** [WildDogTeam/wilddog-token-generator-node#1]
通过该生成器生成的Token传回客户端，客户端发起请求显示 The supplied auth token was invalid

**Comment by jnduan** [comment]
您好，请使用分支`feature-auth-v2`生成token，方法签名与之前版本一致，但`data`参数必须传入`uid`属性（admin token的uid请传空字符串）。

如在使用中有其他问题，欢迎随时发起issue。谢谢。

**Comment by stackOverMind** [comment]
@jnduan  男哥，发下npm吧

**Comment by jnduan** [comment]
npm repo 已发布
@dingyiming 现在可以通过 `npm install wilddog-token-generator` 安装最新的 customToken 生成器了。README 也已更新，如有问题欢迎随时 issue 我们，谢谢。
